AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  S3DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: s3-dependencies
      Description: Dependencies for s3 bucker access
      ContentUri: nodejs/
      CompatibleRuntimes:
        - nodejs8.10      
      RetentionPolicy: Retain